### ISSUE TITLE
unpack failed 

### ISSUE THREAD

**Issue by excllent123** [ash255/matlab_pfile_unpack#1]
Hi  ash255,

In most case,your tool works well,but i find some file unpacke failed, Could you help debug it , it seems that unzip  file failed

Thanks
[calculateC.zip](https://github.com/ash255/matlab_pfile_unpack/files/8470957/calculateC.zip)

**Comment by excllent123** [comment]
是的  旧版本，我自己debug来看似乎是解压的地方，头文件不匹配的错误

**Comment by ukdt** [comment]
初学者想请教一下大佬们，如何利用您上传的代码来将.P转换成.m文件呢？（尴尬）
