### ISSUE TITLE
你好请问该如何使用？

### ISSUE THREAD

**Issue by Dimple-Shang** [ash255/matlab_pfile_unpack#2]
我想对一个P文件转换成.m文件，但是没看到您的库里面有.exe程序
1258183297@qq.com 这是我的邮箱，期待您的回答，我将非常感谢！

**Comment by ash255** [comment]
https://github.com/ash255/matlab_pfile_unpack/releases/tag/v1.0

**Comment by ash255** [comment]
下载第一个ptom.zip

**Comment by Dimple-Shang** [comment]
感谢您的帮助！

**Comment by Dimple-Shang** [comment]
感谢您的帮助！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月22日(星期天) 晚上8:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ash255/matlab_pfile_unpack] 你好请问该如何使用？ (Issue #2)





 
https://github.com/ash255/matlab_pfile_unpack/releases/tag/v1.0

**Comment by Dimple-Shang** [comment]
我运行ptom.exe ，进入如下界面 我任意按键，程序直接就推出了。
大哥 这个该咋使用？你有联系方式吗？教教我吧 谢谢！
![image](https://user-images.githubusercontent.com/95519915/169697713-f278e0d9-9299-45ca-a3c9-67baa2fa766f.png)

**Comment by Dimple-Shang** [comment]
你有联系方式吗？ 我联系你

**Comment by Dimple-Shang** [comment]
[matlab2020b-runtime9.9.zip](https://github.com/ash255/matlab_pfile_unpack/files/8751234/matlab2020b-runtime9.9.zip)
压缩包包含两个P文件，以及你在看雪论坛要求所提供的额外文件

**Comment by ash255** [comment]
你用这个最新版本的
https://github.com/ash255/matlab_pfile_unpack/releases/tag/v1.3
这个可以将当前目录下的所有p文件解密，记得看下使用说明

**Comment by Dimple-Shang** [comment]
大哥 我看了最新使用说明 然后我使用你给我发的这个但是一运行出现报错
安.:
找不到VCRUNTIME140_1D.dll
MSVCP140D.dll
ucrtbased.dll

**Comment by Dimple-Shang** [comment]
谢谢大哥的帮助 转换成功！

**Comment by hangxiaotian** [comment]
> 谢谢大哥的帮助 转换成功！

我出现了和你同样的问题，你是怎么解决的呢，大哥？
