### ISSUE TITLE
又遇到无法解析的问题。

### ISSUE THREAD

**Issue by lixint** [ash255/matlab_pfile_unpack#7]
大佬我又来了，
这次的代码和之前的代码差不多结构，都是fprintf各种内容，但解析不出来。附件是p文件和对应的m文件。
我大概定位到了ptom.cpp的596行。解析某些代码的时候走到这里会报错，但是我不懂C++，弄不明白。
附件这段代码很奇怪，注释掉其中固定的几行，有时候能解析，但改一下再改回去，重新pcode一下可能又解析不了了。
但保留所有的行肯定是解析不了。
[DecodeTestLong.zip](https://github.com/ash255/matlab_pfile_unpack/files/10980953/DecodeTestLong.zip)

**Comment by ash255** [comment]
已经修复好了
